name: CI/CD Pipeline for Avante Garde Backend

on:
  push:
    branches:
      - main  # Run pipeline when pushing to `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the JAR file (Skipping Tests)
      - name: Build JAR file
        run: mvn clean package -DskipTests

      # Step 4: Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 5: Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend

      # Step 7: Deploy to Remote Server (EC2, VPS, etc.)
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend
            docker stop avante_garde_backend || true
            docker rm avante_garde_backend || true
            docker run -d --name avante_garde_backend -p 9900:9900 \
              --network avante_garde_network \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/avante_garde \
              -e SPRING_DATASOURCE_USERNAME=stephen \
              -e SPRING_DATASOURCE_PASSWORD=Steve@123 \
              ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend
