name: CI/CD Pipeline for Avante Garde Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend:latest

      # Debugging step to log secret presence (avoid logging actual values)
      - name: Check Secrets
        run: |
          echo "Host set: ${{ secrets.SERVER_HOST != '' }}"
          echo "User set: ${{ secrets.SERVER_USER != '' }}"
          echo "Key set: ${{ secrets.SERVER_SSH_KEY != '' }}"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          debug: true
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend:latest
            docker stop avante_garde_backend || true
            docker rm avante_garde_backend || true
            docker network create avante_garde_network || true
            docker run -d --name avante_garde_backend -p 9900:9900 \
              --network avante_garde_network \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/avante_garde \
              -e SPRING_DATASOURCE_USERNAME=stephen \
              -e SPRING_DATASOURCE_PASSWORD=Steve@123 \
              ${{ secrets.DOCKERHUB_USERNAME }}/avante_garde_backend:latest